# To use:
#   $ conda env create -f environment.yml
#   $ conda activate <name>
name: machinelearnear-autogluon
dependencies:
  - python=3.9
  - pip
  - nb_conda_kernels
  - ipykernel
  - ipywidgets
  - gh
  - pip:
    - -r requirements.txt